# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         psmon
version:      1.39
version_from: bin/psmon
installdirs:  site
requires:
    Config::General:               0
    Getopt::Long:                  0
    Net::SMTP:                     0
    POSIX:                         0
    Proc::ProcessTable:            0
    Unix::Syslog:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
